#ifndef ISR80H_H
#define ISR80H_H


enum SystemCommands {
  SYSTEM_COMMAND0_SUM,
  SYSTEM_COMMAND1_PRINT,
  SYSTEM_COMMAND1_GETKEY,
  SYSTEM_COMMAND1_PUTCHAR,
  SYSTEM_COMMAND4_MALLOC,
  SYSTEM_COMMAND5_FREE
};

void isr80h_register_commands();

#endif